{% set name = "msmtools" %}
{% set version = "1.1.4" %}
{% set sha256 = "ce4690748358f9b62dbebca1917426ecd6b6c298f436b90480012b245765de53" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cython >=0.24
    - numpy x.x
  run:
    - python
    - numpy x.x
    - scipy
    - six
    - decorator

test:
  imports:
    - msmtools 

about:
  home: http://github.com/markovmodel/msmtools
  license: LGPL-3 
  license_file: LICENSE.txt
  summary: 'Tools for estimating and analyzing Markov state models'
  description: |
    'msmtools is an open source collection of algorithms for the estimation
     and analysis of discrete state space Markov chains via Markov state models (MSM)'

extra:
  recipe-maintainers:
    - marscher 
